/* iPad/iOS touch compatibility for Eaglercraft 1.20.x */
(function(){
"use strict";
var d=document,w=window,canvas=null,locked=false,target=null,controls=false,lastX=0,lastY=0,touches={},keys={};
function ev(name){try{d.dispatchEvent(new Event(name));}catch(e){var x=d.createEvent("Event");x.initEvent(name,true,false);d.dispatchEvent(x);}}
try{Object.defineProperty(d,"pointerLockElement",{configurable:true,get:function(){return locked?target:null;}});}catch(e){}
function showControls(){if(controls)return;controls=true;buildControls();}
function lock(el,show){canvas=el;target=el;locked=true;el.style.cursor="none";ev("pointerlockchange");if(show)showControls();}
d.exitPointerLock=function(){locked=false;target=null;if(canvas)canvas.style.cursor="default";ev("pointerlockchange");};
function mouse(type,x,y,button,buttons,dx,dy){if(!canvas)return;var e;try{e=new MouseEvent(type,{bubbles:true,cancelable:true,view:w,clientX:x,clientY:y,screenX:x,screenY:y,button:button||0,buttons:buttons||0,movementX:dx||0,movementY:dy||0});}catch(z){e=d.createEvent("MouseEvent");e.initMouseEvent(type,true,true,w,0,x,y,x,y,false,false,false,false,button||0,null);}try{Object.defineProperty(e,"movementX",{value:dx||0});Object.defineProperty(e,"movementY",{value:dy||0});}catch(z){}canvas.dispatchEvent(e);}
var kc={KeyW:87,KeyA:65,KeyS:83,KeyD:68,Space:32,ShiftLeft:16,Escape:27,KeyE:69,KeyQ:81,KeyF:70,KeyT:84};
function key(code,key,type){var n=kc[code]||0,e=new KeyboardEvent(type,{bubbles:true,cancelable:true,key:key||code,code:code,keyCode:n,which:n});try{Object.defineProperty(e,"keyCode",{value:n});Object.defineProperty(e,"which",{value:n});}catch(z){}d.dispatchEvent(e);}
function down(c,k){if(!keys[c]){keys[c]=1;key(c,k,"keydown");}}function up(c,k){if(keys[c]){keys[c]=0;key(c,k,"keyup");}}
function install(c){if(!c||c.__ipadTouch){return;}c.__ipadTouch=1;canvas=c;c.style.touchAction="none";
c.requestPointerLock=function(){lock(c,true);};
c.addEventListener("touchstart",function(e){if(!e.changedTouches.length)return;var t=e.changedTouches[0];touches[t.identifier]={x:t.clientX,y:t.clientY,sx:t.clientX,sy:t.clientY,moved:false};lastX=t.clientX;lastY=t.clientY;
if(!locked)lock(c,false);mouse("mousedown",t.clientX,t.clientY,0,1,0,0);e.preventDefault();},{passive:false});
c.addEventListener("touchmove",function(e){var t=e.touches[0],s=t&&touches[t.identifier];if(s){if(Math.abs(t.clientX-s.sx)+Math.abs(t.clientY-s.sy)>8)s.moved=true;}if(locked&&t){var dx=t.clientX-lastX,dy=t.clientY-lastY;lastX=t.clientX;lastY=t.clientY;if(dx||dy)mouse("mousemove",t.clientX,t.clientY,0,1,dx,dy);}e.preventDefault();},{passive:false});
c.addEventListener("touchend",function(e){if(!e.changedTouches.length)return;var t=e.changedTouches[0],s=touches[t.identifier];mouse("mouseup",t.clientX,t.clientY,0,0,0,0);delete touches[t.identifier];e.preventDefault();},{passive:false});
c.addEventListener("touchcancel",function(e){mouse("mouseup",lastX,lastY,0,0,0,0);touches={};e.preventDefault();},{passive:false});}
function btn(root,id,label,x,y,downfn,upfn){var b=d.createElement("div");b.id=id;b.textContent=label;b.style.cssText="position:absolute;"+x+";"+y+";width:64px;height:64px;border:2px solid rgba(255,255,255,.6);border-radius:50%;background:rgba(30,30,30,.45);color:white;display:flex;align-items:center;justify-content:center;font:bold 13px Arial;pointer-events:auto;box-sizing:border-box;-webkit-user-select:none;user-select:none;-webkit-tap-highlight-color:transparent;";b.addEventListener("touchstart",function(e){e.preventDefault();e.stopPropagation();downfn&&downfn();},{passive:false});b.addEventListener("touchend",function(e){e.preventDefault();e.stopPropagation();upfn&&upfn();},{passive:false});b.addEventListener("touchcancel",function(e){e.preventDefault();e.stopPropagation();upfn&&upfn();},{passive:false});root.appendChild(b);return b;}
function buildControls(){var st=d.createElement("style");st.textContent="#ipad-controls{position:fixed;inset:0;z-index:2147483647;pointer-events:none;touch-action:none}#ipad-joy{position:absolute;left:22px;bottom:22px;width:140px;height:140px;border:2px solid rgba(255,255,255,.4);border-radius:50%;background:rgba(30,30,30,.25);pointer-events:auto;box-sizing:border-box}#ipad-knob{position:absolute;left:44px;top:44px;width:48px;height:48px;border-radius:50%;background:rgba(255,255,255,.45);border:2px solid rgba(255,255,255,.55);box-sizing:border-box}";d.head.appendChild(st);
var r=d.createElement("div");r.id="ipad-controls";var j=d.createElement("div");j.id="ipad-joy";var k=d.createElement("div");k.id="ipad-knob";j.appendChild(k);r.appendChild(j);d.body.appendChild(r);
var jid=null,cx=0,cy=0;function set(dx,dy){k.style.transform="translate("+dx+"px,"+dy+"px)";var dead=12;if(dy<-dead)down("KeyW","w");else up("KeyW","w");if(dy>dead)down("KeyS","s");else up("KeyS","s");if(dx<-dead)down("KeyA","a");else up("KeyA","a");if(dx>dead)down("KeyD","d");else up("KeyD","d");}
function jm(t){var dx=t.clientX-cx,dy=t.clientY-cy,l=Math.hypot(dx,dy),m=45;if(l>m){dx=dx/l*m;dy=dy/l*m;}set(dx,dy);}
j.addEventListener("touchstart",function(e){var t=e.changedTouches[0];jid=t.identifier;var q=j.getBoundingClientRect();cx=q.left+70;cy=q.top+70;jm(t);e.preventDefault();e.stopPropagation();},{passive:false});j.addEventListener("touchmove",function(e){for(var i=0;i<e.changedTouches.length;i++)if(e.changedTouches[i].identifier===jid)jm(e.changedTouches[i]);e.preventDefault();e.stopPropagation();},{passive:false});function jr(e){for(var i=0;i<e.changedTouches.length;i++)if(e.changedTouches[i].identifier===jid){jid=null;k.style.transform="translate(0,0)";up("KeyW","w");up("KeyA","a");up("KeyS","s");up("KeyD","d");}e.preventDefault();e.stopPropagation();}j.addEventListener("touchend",jr,{passive:false});j.addEventListener("touchcancel",jr,{passive:false});
btn(r,"ipad-jump","JUMP","right:22px","bottom:110px",function(){down("Space"," ");},function(){up("Space"," ");});
btn(r,"ipad-attack","ATK","right:100px","bottom:22px",function(){mouse("mousedown",0,0,0,1,0,0);},function(){mouse("mouseup",0,0,0,0,0,0);});
btn(r,"ipad-use","USE","right:22px","bottom:22px",function(){mouse("mousedown",0,0,2,2,0,0);},function(){mouse("mouseup",0,0,2,0,0,0);});
btn(r,"ipad-sneak","SNEAK","right:100px","bottom:100px",function(){down("ShiftLeft","Shift");},function(){up("ShiftLeft","Shift");});
btn(r,"ipad-inv","INV","right:178px","bottom:22px",function(){down("KeyE","e");up("KeyE","e");});
}
var oa=Element.prototype.appendChild;Element.prototype.appendChild=function(el){var r=oa.call(this,el);if(el&&el.tagName==="CANVAS")install(el);return r;};var oi=Node.prototype.insertBefore;Node.prototype.insertBefore=function(el,ref){var r=oi.call(this,el,ref);if(el&&el.tagName==="CANVAS")install(el);return r;};function scan(){var c=d.getElementsByTagName("canvas");for(var i=0;i<c.length;i++)install(c[i]);}scan();w.addEventListener("load",scan);w.setInterval(scan,1000);
})();
